# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish ChesterDevs.Core.Aspnet/ChesterDevs.Core.Aspnet.sln --configuration $(buildConfiguration) --self-contained --runtime win-x64 --framework netcoreapp2.1
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/ChesterDevs.Core.Aspnet/ChesterDevs.Core.Aspnet/bin/Release/netcoreapp2.1/win-x64/publish/'
    artifactName: website-files
